# Use Ctrl+a instead of Ctrl+b
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Vim-like navigation
setw -g mode-keys vi

# Split panes
bind | split-window -h
bind - split-window -v

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Mouse support
set -g mouse on

# Faster escape for Neovim
set -sg escape-time 10
